### PR TITLE
HW 3 basic data wrangling - Justin Flattery

### PR DESCRIPTION
**Pull request by jflattery1**

### CODE REVIEW

**Comment by advaitsharma7** [comment]
Please make sure your .Rmd file compiles before you send a pull request.

**Comment by advaitsharma7** [comment]
I request you to please correct your .Rmd file and resend the pull request

**Comment by jflattery1** [comment]
Not sure what you mean by this, I thought it had correctly run on my
Rmarkdown before committing and sending it to Git?

**Comment by advaitsharma7** [comment]
It's not running on my side. Plus it's also not in a directory. Please refer to how the welcome post is set up.

**Pull request closed without merging**
